### ISSUE TITLE
installation from pip doesn't install pandas

### ISSUE THREAD

**Issue by ganow** [KamitaniLab/bdpy#64]
Behavior:

```bash
$ pip freeze  # nothing is installed here
$ pip install bdpy
...
$ pip freeze
bdpy==0.19
h5py==3.8.0
hdf5storage==0.1.19
joblib==1.2.0
numpy==1.24.3
PyYAML==6.0
scikit-learn==1.2.2
scipy==1.10.1
threadpoolctl==3.1.0
$ pip freeze | grep pandas  # we doesn't see the name of pandas
$
```

As a result:
```bash
$ python
Python 3.10.12 (main, Jun  7 2023, 19:32:10) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdpy  # OK
>>> from bdpy import dataform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/bdpy/dataform/__init__.py", line 7, in <module>
    from .pd import *
  File "/usr/local/lib/python3.10/site-packages/bdpy/dataform/pd.py", line 10, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
>>>

**Comment by ganow** [comment]
This could be resolved by merging #67
